# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LyreBird' do 
  use_frameworks!
pod 'Alamofire', '~> 4.8.2'
pod 'SwiftyJSON', '~> 4.0'
pod 'AlamofireImage', '~> 3.5'
pod 'RealmSwift'
  pod 'ObjectMapper'
  # Pods for LyreBird

  target 'LyreBirdTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LyreBirdUITests' do
    # Pods for testing
  end

end
